# Generated by Django 4.1.5 on 2023-01-19 11:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_user_first_name_remove_user_tc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.getFileName),
        ),
    ]
